### ISSUE TITLE
The intero package is not being used correctly in Emacs

### ISSUE THREAD

**Issue by OmanF** [vic/asdf-haskell#1]
After installing `asdf` and `Haskell`, re-shiming and setting it as global (via `asdf global haskell 8.0.1`), I installed `intero` via `stack install intero` (among other packages).
To be on the safe-side I re-shimmed, again, after installing `stack`.

I then started Emacs, which I have set to use `intero` as `Haskell`'s backend (through the packages settings) and am getting the following error message:
```haskell
The process ended. Here is the reason that Emacs gives us:

  exited abnormally with code 1

For troubleshooting purposes, here are the arguments used to launch intero:

  stack ghci ghci --with-ghc intero "--docker-run-args=--interactive=true --tty=false" --no-build --no-load --ghci-options -odir=/home/ohadfk/.asdf/installs/haskell/8.0.1/stack/global-project/.stack-work/intero/intero23512Ud2 --ghci-options -hidir=/home/ohadfk/.asdf/installs/haskell/8.0.1/stack/global-project/.stack-work/intero/intero23512Ud2
```
Seems any run on Haskell creates a separate folder for `intero` (maybe for other plugins as well, I don't know if any of them came into use on the boot) with a unique ID (which is appended to the `intero` name).
I checked those folders... they are empty (as in showing 0 content on `ls -a`, empty).

(If there's any more info I need to provide let me know).

**Comment by vic** [comment]
Hey, havent used `intero` with emacs. After `stack install intero` and `asdf reshim haskell` you should have the correct `intero` in your PATH. Dont know if your emacs is finding the correct `intero` executable (inside your asdf haskell installation), what happens if  you try to execute intero command from a bash shell, does it work as expected? My first guess is that emacs might not be using the asdf environment to find the executable.

**Comment by OmanF** [comment]
Hey.
I've switched from Emacs to Atom for a while, and since Atom doesn't need Intero, I can't answer your question right now.

Since I switched, and seem to be the only one who had the issue, I'll now close it.
If I ever switch back and encounter the issue again I'll reopen the issue and post relevant details.

Thanks all the same!
